CFLAGS=-Wall -O3 -I/c/OSGeo4W/include -fopenmp
LDFLAGS=-O3 -fopenmp

all: meffa.exe

clean:
	$(RM) *.o

meffa.exe: main.o raster.o accumulate.o timeval_diff.o
	$(CC) $(LDFLAGS) -o $@ $^ /c/OSGeo4W/lib/gdal_i.lib

%.o: %.c
	$(CC) $(CFLAGS) -c $<
